name: BCIT Services Python Application

on:
  push:
    branches: [ "testing" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Init Database
        run: |
          python ./manage.py
      - name: Test with pytest
        run: |
          python -m pytest
  create-pull-request:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Create pull request
        run: gh pr create -B dev -H ${{ github.ref_name }} --title "Merge ${{ github.ref_name }} into dev" --body "Automated PR via Github Actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: github.com/Gabe-CIT/TermProject